name: Update GitHub Streak Daily

on:
  schedule:
    cron: '14 0 * * *'  # Todos los días a las 00:14 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Update README with current date
        run: |
          sed -i "s/timestamp=[0-9]\+/timestamp=${{ steps.date.outputs.date }}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add README.md
          git commit -m "Update GitHub Streak image timestamp to ${{ steps.date.outputs.date }}" || echo "No changes to commit"
          git push
